<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Welcome_UserData.Password</name>
   <tag></tag>
   <elementGuidId>385e8c83-842f-4c78-a49a-65314b977e9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UserData_Password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UserData_Password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffdc25a0-1445-4c51-ada2-e9edae4fee7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-solid h-auto py-6 px-6 rounded-lg</value>
      <webElementGuid>bb559e7b-f48f-4b21-8e4f-6af4a21c6fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>16e3a48d-2b49-494c-afc6-4b9d20f42ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>3f354302-43c0-4f1c-838c-4c1765387493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UserData_Password</value>
      <webElementGuid>a7491e01-5169-41bf-8d80-2e5849467b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UserData.Password</value>
      <webElementGuid>3e551581-62e7-4ab8-a0d3-c7d72af292b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UserData_Password&quot;)</value>
      <webElementGuid>d0160a2f-1203-4327-8c48-29e5d92f9ced</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UserData_Password']</value>
      <webElementGuid>0d163ea9-8c2b-4b96-9ad4-caafdee89853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_login']/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>632700c5-9bbd-4693-87f8-69208296ff16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>a85a6ff8-2cc6-4bfe-8148-40de39012176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Password' and @id = 'UserData_Password' and @name = 'UserData.Password']</value>
      <webElementGuid>ef8d8061-b514-4733-a787-8b13f1f36495</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
