<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Umar</name>
   <tag></tag>
   <elementGuidId>1ef57f91-afb3-4ba7-acbc-3830d7aff28f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.text-dark-50.font-weight-bolder.font-size-base.d-none.d-md-inline.mr-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_quick_user_toggle']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#kt_quick_user_toggle >> internal:text=&quot;Umar&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8974c067-1363-445b-845a-fccb2545d803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-dark-50 font-weight-bolder font-size-base d-none d-md-inline mr-3</value>
      <webElementGuid>462ac993-bb49-4953-ac29-96e6366aff46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Umar</value>
      <webElementGuid>686a269d-435d-4596-a906-8cf18685f3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_quick_user_toggle&quot;)/span[@class=&quot;text-dark-50 font-weight-bolder font-size-base d-none d-md-inline mr-3&quot;]</value>
      <webElementGuid>7b182ff7-02f7-4223-94a7-05938b86a9a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_quick_user_toggle']/span[2]</value>
      <webElementGuid>09976e18-9a92-4079-814b-bd7ae6e89c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi,'])[1]/following::span[1]</value>
      <webElementGuid>0445d717-d88e-490c-bd7a-2c3e8f5d9b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase'])[1]/following::span[2]</value>
      <webElementGuid>f059f4ff-b8c5-4499-a03d-ea8473bb9bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Training Need Identification Record'])[3]/preceding::span[1]</value>
      <webElementGuid>887f9c6e-fee3-4e98-a2aa-bfa39a1111a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From Date'])[1]/preceding::span[1]</value>
      <webElementGuid>0cecab77-e2b4-4f35-b63f-4d1a4fe2f8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Umar']/parent::*</value>
      <webElementGuid>d8de4e5b-cb9e-4df6-879d-5ca20d763042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>d28bc10b-d7fe-4bfe-84f8-c9eb7abf10aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Umar' or . = 'Umar')]</value>
      <webElementGuid>ab2fb5cc-61ad-495d-a01a-3b3c5cb4afcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
